### ISSUE TITLE
System styles not being applied

### ISSUE THREAD

**Issue by SjoerdV** [manuth/MarkdownConverter#60] opened 2020-11-24 16:58 UTC
Seems like system default styles are not being applied anymore when exporting to pdf. 
VSCode: 1.51.1
Extension: 3.1.2

Possibly related reference issue: https://github.com/manuth/MarkdownConverter/issues/6

**Comment by malustewart** [comment] 2021-04-23 12:44
I think I'm experiencing the same bug but am not sure. 
A year ago, my pdfs used to render like this:
![image](https://user-images.githubusercontent.com/23437944/115872340-139a9400-a418-11eb-9a17-9ddd82f8b928.png)
But now they render like this:
![image](https://user-images.githubusercontent.com/23437944/115872486-3e84e800-a418-11eb-84c3-2b7453b989ca.png)

I never touched any stylesheet configuration. 

Is it the same bug or should I open another issue? Is it even a bug?

**Comment by manuth** [comment] 2021-04-23 13:41
@malustewart I'm terribly sorry for you experiencing this issue.
If I remember correctly, the cause of this issue is a change of the directory structure of VSCode's builtin markdown-extension.
I'll fix this error as soon as possible and will package a new version of this extension.

Stay tuned

**Comment by manuth** [comment] 2021-09-12 09:37
Sorry for letting you guys wait for such a long time.
I had an error in the insertion of style-sheets causing the system-styles to not load.

This issue has been fixed in 40b26cf1b93f6e030a3552fcdbd8bb170b663494.

The system styles will work again in the next release.

**Closed** 2021-09-19 22:16 UTC
Labels: bug
