### ISSUE TITLE
PDF export produces file with 404 error instead of text

### ISSUE THREAD

**Issue by HughxDev** [manuth/MarkdownConverter#61] opened 2020-12-03 16:10 UTC
File just says:

> 404
> The requested path could not be found

**Markdown Coverter**
v3.1.2

**VS Code**
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by manuth** [comment] 2021-01-06 10:29
Hello @hguiney
Sadly I couldn't reproduce the issue. I just created a macOS VM in order to try it out and it's working fine for me.
Could you please create a repository containing your markdown-workspace for me to reproduce the issue?

**Comment by JoeJoeTV** [comment] 2021-01-09 13:04
I have the same Issue, it just shows a 404 error page.

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Datum: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Linux x64 5.4.0-60-generic

**Comment by manuth** [comment] 2021-01-14 12:17
Thanks for confirming the error

Sadly I still wasn't able to find the reason for the error to occur.
Are you working in a `.code-workspace`, a single directory or are you editing a single file when the error occurs?

**Comment by damgot** [comment] 2021-02-10 10:09
Hello, same for me.

I've got a 404 pdf.

I'm using a single md file (no workspace or directory, just single file).

**Comment by manuth** [comment] 2021-02-10 10:56
Sadly I still find myself unable to reproduce the error.
I suspect the error must be somwhere here:
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/Conversion/Converter.ts#L177-L186

If the markdown-file with a leading `.html` is requested (for example `/Test.md.html`), the rendered document should be returned by the web server (the `if`-branch).
But it looks like the code enters the `else`-branch for you guys who expire this issue.

Sadly I'm not quite sure what might be causing this issue.

@damgot do you think you're able to once more clone the code, add a breakpoint to line 177 and tell me contents of the variables `request.url` and `this.WebDocumentName`?

Thanks for being patient
Kind regards

**Comment by damgot** [comment] 2021-02-12 08:34
Hello,
Unfortunattely, I'm not able to debug it. I've following errors : 

Command 'Markdown: Convert Document' resulted in an error (command 'markdownConverter.Convert' not found)

Activating extension 'manuth.markdown-converter' failed: Cannot find module 'c:\Proj\MarkdownConverter\lib\index.js' Require stack: - c:\Users\Damgot\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js - c:\Users\Damgot\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js - c:\Users\Damgot\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

Do you know what is wrong ?
Thanks

**Comment by manuth** [comment] 2021-02-12 08:43
That's weird. Maybe the code failed to build before debugging the code...

**Comment by damgot** [comment] 2021-02-15 14:24
I tried the extension without any options and it seems to work with very simple md file.

However, the image syntax "![alternate] (path to image)" seems no longer work.

The text is print in the pdf, instead of the image.

![2021-02-15 15_23_35-Untitled-1 pdf - Adobe Acrobat Reader DC (32-bit)](https://user-images.githubusercontent.com/4757987/107958164-e9ed6880-6fa1-11eb-83dc-fa6df306dea1.png)

**Comment by FabianSchuster** [comment] 2021-02-17 08:15
Hey,
I have nearly the same issue...
In my case the error is just there when I include images.

Error: net::ERR_EMPTY_RESPONSE at http://localhost:46835/Markdown_template.md.html

When it comes to Text i have no issues
About my system:
- Linux Pop!_OS 20.10  64-bit

I hope i could help you!

**Comment by damgot** [comment] 2021-02-18 08:20
Hello all,
It seems it's not a bug with markdownConverter but with VSCode.

There are a lot of problem with image interpretation in markdown file with the last 1.53 vscode version. It seems downgrade to 1.52.1 solve the issue. 

So @manuth , don't worry, the problem is not on your side.

**Comment by manuth** [comment] 2021-02-18 20:23
@damgot thank you very much for pointing this out, that's very useful!
@hguiney, @JoeJoeTV is your issue probably related to the inproper picture-handling as pointed out by @damgot?

**Comment by manuth** [comment] 2021-02-19 00:06
I was able to find the issue (inside the `markdown-language-features` extension) which caused markdown-files containing pictures to throw errors.

I implemented a workaround which will be included in the upcoming version.
Also I opened up an issue in the vscode-repository: https://github.com/microsoft/vscode/issues/116987

@hguiney, @JoeJoeTV please let me know whether your documents contains pictures and also check whether it's working properly using vscode 1.52.1.

**Comment by richardy706** [comment] 2021-05-21 13:17
I am having the same 404 issue when converting to PDF.  My document does not have any images but does have fenced code blocks.
Version: 3.1.2
VS Code: 1.56.2
Windows: 10.0.19042

**Comment by damgot** [comment] 2021-05-25 15:32
Also have the bug with VS.Code 1.56.2.

It's a Visual Studio Code bug

**Comment by damgot** [comment] 2021-05-25 16:01
Also : Please be sure to not use any special character in your md filename and/or folder name.
The absolute path to the md filename need to have no accent at all.

**Comment by manuth** [comment] 2021-05-25 19:20
Thanks für looking into the matter - I'll make sure to work on MarkdownConverter again as soon as I can

Sorry for letting you guys wait for so long

**Comment by manuth** [comment] 2021-09-11 00:21
> Also : Please be sure to not use any special character in your md filename and/or folder name.
> The absolute path to the md filename need to have no accent at all.

Thanks a ton for pointing this out!
This helped me a lot to solve the issue.

I finally got some time left for working on the MarkdownConverter again.

Stay tuned

**Closed** 2021-09-19 22:15 UTC
Labels: bug
