### ISSUE TITLE
"command 'markdownConverter.convert' not found" following update 06.01.2022

### ISSUE THREAD

**Issue by DaveyJH** [manuth/MarkdownConverter#139] opened 2022-01-06 23:23 UTC
Hi, I successfully converted a document this morning (around 0830 GMT) with no issue. When I try to convert (or convert all) I now (2300 GMT) receive the error shown below. I have tried uninstalling the extension and re-installing, restarting VSCode and my laptop. I am only a junior dev so apologies if I have missed something following the latest release but it appears the functionality has broken. Appreciate if you are able to take a look or offer any advice.

## Error Message
![image](https://user-images.githubusercontent.com/80708826/148465713-865e297e-4a68-4006-aeae-637c03320c03.png)

### MarkdownConverter in settings.json
![image](https://user-images.githubusercontent.com/80708826/148465722-7d7b81f7-17a6-4c68-85d4-67a6a0d0860d.png)

### VSCode Info
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by manuth** [comment] 2022-01-06 23:32
Hello @DaveyJH 
Sorry for the inconvenience and thanks for reporting the issue.
I just successfully tried to reproduce this error.

I'll try to get this issue fixed ASAP.
Sorry for the inconvenience

**Comment by DaveyJH** [comment] 2022-01-06 23:35
Hi, Glad you were able to reproduce the error and it wasn’t just my rookie mistake somewhere.Happy to re-try when you believe you have resolved the issue. Thanks for providing a great extension! Dave Sent from Mail for Windows From: Manuel ThalmannSent: 06 January 2022 23:32To: manuth/MarkdownConverterCc: DaveyJH; MentionSubject: Re: [manuth/MarkdownConverter] "command 'markdownConverter.convert' not found" following update 0601.2022 (Issue #139) Hello @DaveyJHSorry for the inconvenience and thanks for reporting the issue.I just successfully tried to reproduce this error.I'll try to get this issue fixed ASAP.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 



	
		
			
				
			
		
		
			
				This email has been checked for viruses by AVG antivirus software.
				www.avg.com

**Comment by manuth** [comment] 2022-01-07 00:08
I could elaborate the issue and to be honest, it looks like it's a rookie programmer issue on my side 🥴 😂 
The issue was caused by changes I made in the webpack-configuration here trying to prevent memory leaks:
https://github.com/manuth/MarkdownConverter/blob/5c3716cc028ededa5ace28b1b97ba50091df1a8f/webpack.config.ts#L109-L111

I'll go fix this - you can expect a new version of MarkdownConverter to be published in about 10-15min.
Thanks for the patience and most importantly thanks for using Markdown Converter 😄

**Comment by manuth** [comment] 2022-01-07 00:30
The new version has been published now. You might have to wait for a bit until the new version shows up in vscode.
Alternatively you can download it from GitHub: https://github.com/manuth/MarkdownConverter/releases/

Please let me know whether the new version is working for you

**Comment by DaveyJH** [comment] 2022-01-07 00:39
I just had to do a reload of the extension in VSCode. All back to normal and working as expected. Really impressed with such a quick turn around. This is my first real reporting of an issue so thanks for making it a good experience 😁

...Just not sure if I should close the issue or if I leave that up to you!

**Comment by manuth** [comment] 2022-01-07 00:50
Glad to call you welcome, then 😄

In case you know the issue has been solved you can of course close the issue yourself if you feel like doing so. When closing an issue it might make sense to post a comment stating as to why you close the issue or stating that the error has been resolved.

If you're not sure whether all aspects of the issue have been resolved entirely you can always play it save and leave the the closing to a contributor (or the repo's owner).

**Closed by manuth** 2022-01-07 00:50 UTC

**Comment by manuth** [comment] 2022-01-07 00:52
Oh yeah... Happy coding and stuff ^^
You reporting issues is most appreciated 😄

**Comment by DaveyJH** [comment] 2022-01-07 00:53
Tested on multiple files following fix. All working as normal :+1:

**Comment by DaveyJH** [comment] 2022-01-07 01:01
Oh, I didn't refresh before writing the last comment and thought I was closing the issue 😅

I knew there would be a rookie mistake by me in there somewhere!

**Comment by manuth** [comment] 2022-01-07 01:02
No worries, these rookie mistakes happen to everyone, I guess 😂
