### ISSUE TITLE
Install didn't work?  

### ISSUE THREAD

**Issue by sjmcdowall** [manuth/MarkdownConverter#31] opened 2019-06-01 20:06 UTC
Tried using it and just get:

command 'markdownConverter.Convert' not found

in an error window.. .

This is on a Mac running the latest: Mojave 10.14.5 with just about everything updated that I know of.

**Comment by manuth** [comment] 2019-06-01 22:19
Hey @sjmcdowall 
Thanks for reporting the bug ^^

This sounds like the main script which adds the commands to VSCode doesn't run correctly on macOS.
I'll take some time to reproduce and fix the error as soon as possible.

**Comment by manuth** [comment] 2019-06-03 12:09
@sjmcdowall sadly both of my computers are not able to run a virtual macOS which means that I can't reproduce the error.

Please make sure you're running the most recent version of Visual Studio Code.

**Comment by manuth** [comment] 2019-06-06 19:59
@sjmcdowall I successfully installed a virtual mac and tested the extension.
I could not reproduce the error, performing a conversion worked for me.

Thus I'm going to close this issue.

**Closed by manuth** 2019-06-06 19:59 UTC
Labels: bug
