### ISSUE TITLE
Issue with H1 as first line

### ISSUE THREAD

**Issue by badchenn** [manuth/MarkdownConverter#5] opened 2017-04-26 17:40 UTC
Something odd occurred with a first line content. Starting the md file with a 'H1' formatted line :

    ------------------------------------------
    1| # Continuous Integration / Continuous Deployment Assessment Guide
    2|
    -------------------------------------------

caused unexpected html output ("view source"):

    <div class="container">
    # Continuous Integration &#x2F; Continuous Deployment Assessment Guide'

Notice how the hashtag was directly transferred and the slash (/) was converted to an html entity

---------

Inserting an empty first line (_sorry, this does not format the way I want on github_):
    ------------------------------------------
    1|
    2| # Continuous Integration / Continuous Deployment Assessment Guide
    3|
    -------------------------------------------

provided properly formatted html H1:

    <div class="container">
    <h1 id="continuous-integration-continuous-deployment-assessment-guide">Continuous Integration / Continuous Deployment Assessment Guide</h1>

NOTE: I removed the slash from the H1 title and returned the heading to line 1 - still had odd output

**Comment by manuth** [comment] 2017-04-26 18:22
Hello - sounds to me as if it's an issue caused by markdown-it.

I will have a look at it in about two weeks.
I'm sorry for letting you wait that long. I'm currently having my final thesis.
Please be patient.

~Manu

**Comment by manuth** [comment] 2017-05-09 20:31
Hello, badchenn

Sadly I couldn't reproduce the error. I just converted exactly the same document-content and the source-code doesn't have any HTML-entities but a normal slash.
Please make sure you're using the most recent version.

Could you please send me the markdown-file you're trying to convert?

**Comment by manuth** [comment] 2017-05-30 13:29
Hello badchenn
Since you didn't answer last few weeks I assume you could solve it on your own.
For that reason I'll close the issue now.

Please feel free to post a comment if you have further questions.

~Manu

**Closed by manuth** 2017-05-30 13:29 UTC
Labels: help wanted
